#!/bin/sh

. prompt.sh

while read file; do
        case "$1" in
	'd')
		prompt -x "Delete ${file}?" \
		    && rm "${file}" \
		    && notify-send 'sxiv' "${file} deleted."
		;;
	'e')
		mtpaint "${file}" &
		;;
	'f')
		convert -flop "${file}" "${file}"
		;;
	'i')
		notify-send 'File information' "$(mediainfo "${file}")"
		;;
	'r')
		convert -rotate 90 "${file}" "${file}"
		;;
	'R')
		convert -rotate -90 "${file}" "${file}"
		;;
	'p')
		dir="${HOME}/pictures/$(
			cd "${HOME}/pictures/" && \
			find . -type d | dmenu -i -l 5 -p "Copy ${file} to?"
		)"
		cp "${file}" "${dir}" \
		    && notify-send 'sxiv' "${file} copied to ${dir}." &
		;;
	'w')
		setbg "${file}" &
		;;
	'y')
		printf '%s' "${file}" | xclip -selection clipboard \
		    && notify-send 'sxiv' "${file} copied to clipboard." &
		;;
	'Y')
		readlink -f "${file}" | xclip -selection clipboard \
		    && notify-send 'sxiv' \
		        "Full path of ${file} copied to clipboard." &
		;;
        esac
done
