#!/bin/sh
# Program:
#	* Preview script built for use with lf
# Dependency:
#	* ext(1)
#	* highlight(1)
#	* mediainfo(1)
#	* pdftotext(1)
# Author:
#       * Chang, Chu-Kuan <cckuan@changchukuan.name>

readonly file="$1"
readonly progname="$(basename "$0")"

ckfsize()
{
	if [ "$(du -k "${file}" | cut -f 1)" -gt '5000' ]; then
		printf '%s: file too large to preview\n' "${progname}"
		exit 0
	fi
}

if [ ! -f "${file}" ]; then
	exit 0
fi
case "${file}" in
*.png|*.jpg|*.jpeg|*.mkv|*.mp3|*.mp4|*.m4v)
	mediainfo "${file}"
	;;
*.pdf)
	ckfsize
	pdftotext "${file}" -
	;;
*.tar|*.tar.bz2|*.tbz2|*.tb2|*.tz2|*.tar.Z|*.taZ|*.tZ|*.tar.gz|*.tgz|*.tar.lzma|*.tlz|*.tar.xz|*.txz|*.7z|*.rar|*.zip)
	ckfsize
	ext -t "${file}"
	;;
#*.html|*.xml)
#	lynx -dump "${file}"
#	;;
*)
	highlight "${file}" -O ansi --force
	;;
esac

