#!/bin/sh

#
# .kshrc for desktop
#

case "$-" in
#
# We are interactive
#
*i*)

#
# Ksh setting
#

set -o vi
set -o vi-tabcomplete

# History
histfile_dir="${XDG_CACHE_HOME:-${HOME}/.cache}/shell"
if [ ! -d "${histfile_dir}" ]; then
	mkdir -p "${histfile_dir}"
fi

HISTFILE="${histfile_dir}/ksh_history"
HISTSIZE='5000'
HISTCONTROL='ignoredups:ignorespace'

#
# Prompt
#

_ps1_user()
{
	case "${UID}" in
	'0')
		# Red root name
		printf '\\[\033[31m\\]%s\\[\033[00m\\]' "${USER}"
		;;
	*)
		# Yellow user name
		printf '\\[\033[33m\\]%s\\[\033[00m\\]' "${USER}"
		;;
	esac
}

_ps1_hostname()
{
        if [ -z "${SSH_CONNECTION}" ]; then
		# Blue hostname
		printf '\\[\033[34m\\]%s\\[\033[00m\\]' "${host}"
        else
		# Red hostname
		printf '\\[\033[31m\\]%s\\[\033[00m\\]' "${host}"
        fi
}

_ps1_pwd()
{
	case "${PWD}" in
	"${HOME}"*)
		printf '\\[\033[33m\\]~%s\\[\033[00m\\]' "${PWD#${HOME}}"
		;;
	*)
		printf '\\[\033[33m\\]%s\\[\033[00m\\]' "${PWD}"
		;;
	esac
}

_ps1_exit_status()
{
	case "$1" in
	'0')
		# Green prompt
		printf '\\[\033[32m\\]%s\\[\033[00m\\]' "${ps1s}"
		;;
	*)
		# Red prompt
		printf '\\[\033[31m\\] %s %s\\[\033[00m\\]' "$1" "${ps1s}"
		;;
	esac
}

# we may have su'ed so reset these
USER="$(id -un)"
UID="$(id -u)"
case "${UID}" in
'0')
	ps1s='# '
	;;
*)
	ps1s='$ '
esac
hostname="${HOSTNAME:-$(uname -n)}"
host="${hostname%%.*}"

PS1="\$(_ps1_user)\[\033[32m\]@\$(_ps1_hostname) \$(_ps1_pwd)
\$(_ps1_exit_status \$?)"
PS2='> '
PS3='#? '
PS4='+ '

#
# Ksh completions / Common aliases and functions
#

ksh_comp_file="${XDG_CONFIG_HOME:-${HOME}/.config}/shell/ksh_completion"
commonrc_file="${XDG_CONFIG_HOME:-${HOME}/.config}/shell/commonrc"
for f in "${ksh_comp_file}" "${commonrc_file}"; do
	if [ -r "$f" ]; then
		. "$f" 
	else
		printf 'kshrc: %s not found\n' "$f" 1>&2
	fi
done

;;
#
# We are non-interactive
#
*)
# Do nothing
;;
esac

